# Generated by Django 2.2 on 2020-07-29 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0012_auto_20200729_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='System.Project'),
        ),
    ]
