# Generated by Django 2.2 on 2020-07-31 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0017_auto_20200731_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_bugs', to='System.Project'),
        ),
    ]
