# Generated by Django 2.2 on 2020-07-29 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_auto_20200729_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default='vishav', on_delete=django.db.models.deletion.CASCADE, to='System.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='System.user'),
        ),
    ]
