# Generated by Django 2.2 on 2020-07-31 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0018_auto_20200731_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='task',
            new_name='project',
        ),
    ]
