# Generated by Django 2.2 on 2020-07-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0019_auto_20200731_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
